services:
  hhvm:
    container_name: theodore-simple-web-token-container
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: .
        target: /mnt/project
    ports:
      - 48556:10641
