/** simple-web-token is MIT licensed, see /LICENSE. */
namespace HTL\SimpleWebToken;

use namespace HH\Lib\Str;
use function base64_encode, rawurldecode, urldecode;

/**
 * @param $decoders_encoders, if one url decoders is passed, it is used for all
 * url decoder operations. If zero are passed, urldecode() is used for data,
 * since the spec requires as such.
 */
function parse_strict(
  string $input,
  shape(
    ?'url_decoder_for_hmac' => Decoder,
    ?'url_decoder_for_data' => Decoder,
    ?'base64_encoder' => Encoder,
    /*_*/
  ) $decoders_encoders = shape(),
)[]: Token {
  $base64_encoder = $decoders_encoders['base64_encoder'] ?? base64_encode<>;
  $url_decoder_for_data = $decoders_encoders['url_decoder_for_data'] ??
    $decoders_encoders['url_decoder_for_hmac'] ??
    urldecode<>;
  // The choice of raw over non-raw matter here. Tokens generated by sign()
  // do not encode their hmac. All 65 base64 characters (the 65th is `=`)
  // will pass unaltered through rawurldecode<>, but not urldecode<>. This
  // means this function can (by default) handle tokens signed with earlier
  // versions of this library, that did not include sign_strict().
  $url_decoder_for_hmac = $decoders_encoders['url_decoder_for_hmac'] ??
    $decoders_encoders['url_decoder_for_data'] ??
    rawurldecode<>;

  $parts = Str\split($input, '&'.Token::HMACSHA256.'=', 2);
  $no_hmac_swt = $parts[0];
  $submitted_hmac =
    idx($parts, 1) |> $$ is null ? null : $url_decoder_for_hmac($$);

  return new Token(
    $no_hmac_swt,
    $submitted_hmac,
    _Private\parse_x_www_form_encoded($no_hmac_swt, $url_decoder_for_data),
    $base64_encoder,
  );
}
